### PR TITLE
fix(dev): stop dev server from uglifying script

### LINKED ISSUE #43: Script minified in dev
The javascript bundle should not be minified when running the dev server.

### PR DESCRIPTION
**Pull request by oysteinsigholt**
Fixes #43

### CODE REVIEW

File: gulpfile.js [hunk 1]
```diff
@@ -78,10 +78,22 @@ gulp.task("script", (cb) => {
...
 });
 
+gulp.task("script:dev", (cb) => {
+    browserify({
+        entries: ["./script/script.js"]
+    })
+        .transform(babelify, { presets: ["es2015"] })
+        .bundle()
+        .pipe(source("script.js"))
+        .pipe(rename("script.js"))
```
Comment (pkkummermo) [inline gulpfile.js]: Do we really need the rename?
